spring:
  datasource:
    url: jdbc:mariadb://localhost:8306/finace-demo
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jackson:
    serialization:
      write_dates_as_timestamps: false
  jpa:
    show-sql: true

logging:
  level:
    root: INFO
  file:
    name: logs/app.log